<?php

class m150825_131022_create_province_tables extends DbMigration {

    public function safeUp() {
        #aree
        $this->createTable('aree', array(
            'AreaID' => self::Pk(),
            'Area' => self::TypeVarchar(50, true),
            'Comuni' => 'int(3) unsigned NOT NULL',
            'Province' => 'int(3) unsigned NOT NULL',
            'Regioni' => 'int(3) unsigned NOT NULL',
            'Popolazione' => self::TypeInt(true),
            'PopolazionePerc' => self::TypeFloat(true),
            self::Pk('AreaID'),
            'UNIQUE KEY unique_aree_area (Area)',
                ), self::TableOptions());
        $this->insertMultiple('aree', array(
            array('AreaID' => '1', 'Area' => 'Italia Nord Occidentale', 'Comuni' => '3059', 'Province' => '25', 'Regioni' => '4', 'Popolazione' => '15861548', 'PopolazionePerc' => '26.6'),
            array('AreaID' => '2', 'Area' => 'Italia Nord Orientale', 'Comuni' => '1480', 'Province' => '22', 'Regioni' => '4', 'Popolazione' => '11521037', 'PopolazionePerc' => '19.3'),
            array('AreaID' => '3', 'Area' => 'Italia Centrale', 'Comuni' => '996', 'Province' => '22', 'Regioni' => '4', 'Popolazione' => '11681498', 'PopolazionePerc' => '19.6'),
            array('AreaID' => '4', 'Area' => 'Italia Meridionale', 'Comuni' => '1790', 'Province' => '24', 'Regioni' => '6', 'Popolazione' => '13980833', 'PopolazionePerc' => '23.4'),
            array('AreaID' => '5', 'Area' => 'Italia Insulare', 'Comuni' => '767', 'Province' => '17', 'Regioni' => '2', 'Popolazione' => '6640311', 'PopolazionePerc' => '11.1'),
        ));
        # regioni
        $this->createTable('regioni', array(
            'RegioneID' => self::Pk(),
            'AreaID' => self::TypeInt(true),
            'Regione' => self::TypeVarchar(50, true),
            'Residenti' => self::TypeInt(true),
            'ResidentiPerc' => self::TypeFloat(true),
            'Superficie' => self::TypeInt(true),
            'SuperficiePerc' => self::TypeFloat(true),
            'Densita' => self::TypeFloat(true),
            'Comuni' => 'int(3) unsigned NOT NULL',
            'Province' => 'int(3) unsigned NOT NULL',
            self::Pk('RegioneID'),
            'UNIQUE KEY unique_regioni_regione (Regione)',
                ), self::TableOptions());
        $this->addForeignKey('fk_regioni_area', 'regioni', 'AreaID', 'aree');
        $this->insertMultiple('regioni', array(
            array('RegioneID' => '1', 'AreaID' => '4', 'Regione' => 'Abruzzo', 'Residenti' => '1312507', 'ResidentiPerc' => '2.2', 'Superficie' => '10795', 'SuperficiePerc' => '3.6', 'Densita' => '121.6', 'Comuni' => '305', 'Province' => '4'),
            array('RegioneID' => '2', 'AreaID' => '4', 'Regione' => 'Basilicata', 'Residenti' => '576194', 'ResidentiPerc' => '1', 'Superficie' => '9995', 'SuperficiePerc' => '3.3', 'Densita' => '57.7', 'Comuni' => '131', 'Province' => '2'),
            array('RegioneID' => '3', 'AreaID' => '4', 'Regione' => 'Calabria', 'Residenti' => '1958238', 'ResidentiPerc' => '3.3', 'Superficie' => '15081', 'SuperficiePerc' => '5', 'Densita' => '129.9', 'Comuni' => '409', 'Province' => '5'),
            array('RegioneID' => '4', 'AreaID' => '4', 'Regione' => 'Campania', 'Residenti' => '5769750', 'ResidentiPerc' => '9.7', 'Superficie' => '13590', 'SuperficiePerc' => '4.5', 'Densita' => '424.6', 'Comuni' => '551', 'Province' => '5'),
            array('RegioneID' => '5', 'AreaID' => '2', 'Regione' => 'Emilia-Romagna', 'Residenti' => '4377487', 'ResidentiPerc' => '7.3', 'Superficie' => '22456', 'SuperficiePerc' => '7.5', 'Densita' => '194.9', 'Comuni' => '348', 'Province' => '9'),
            array('RegioneID' => '6', 'AreaID' => '2', 'Regione' => 'Friuli-Venezia Giulia', 'Residenti' => '1221860', 'ResidentiPerc' => '2', 'Superficie' => '7855', 'SuperficiePerc' => '2.6', 'Densita' => '155.6', 'Comuni' => '218', 'Province' => '4'),
            array('RegioneID' => '7', 'AreaID' => '3', 'Regione' => 'Lazio', 'Residenti' => '5557276', 'ResidentiPerc' => '9.3', 'Superficie' => '17208', 'SuperficiePerc' => '5.7', 'Densita' => '323', 'Comuni' => '378', 'Province' => '5'),
            array('RegioneID' => '8', 'AreaID' => '1', 'Regione' => 'Liguria', 'Residenti' => '1565127', 'ResidentiPerc' => '2.6', 'Superficie' => '5421', 'SuperficiePerc' => '1.8', 'Densita' => '288.7', 'Comuni' => '235', 'Province' => '4'),
            array('RegioneID' => '9', 'AreaID' => '1', 'Regione' => 'Lombardia', 'Residenti' => '9794525', 'ResidentiPerc' => '16.4', 'Superficie' => '23863', 'SuperficiePerc' => '7.9', 'Densita' => '410.5', 'Comuni' => '1544', 'Province' => '12'),
            array('RegioneID' => '10', 'AreaID' => '3', 'Regione' => 'Marche', 'Residenti' => '1545155', 'ResidentiPerc' => '2.6', 'Superficie' => '9366', 'SuperficiePerc' => '3.1', 'Densita' => '165', 'Comuni' => '239', 'Province' => '5'),
            array('RegioneID' => '11', 'AreaID' => '4', 'Regione' => 'Molise', 'Residenti' => '313341', 'ResidentiPerc' => '0.5', 'Superficie' => '4433', 'SuperficiePerc' => '1.5', 'Densita' => '70.7', 'Comuni' => '136', 'Province' => '2'),
            array('RegioneID' => '12', 'AreaID' => '1', 'Regione' => 'Piemonte', 'Residenti' => '4374052', 'ResidentiPerc' => '7.3', 'Superficie' => '25402', 'SuperficiePerc' => '8.4', 'Densita' => '172.2', 'Comuni' => '1206', 'Province' => '8'),
            array('RegioneID' => '13', 'AreaID' => '4', 'Regione' => 'Puglia', 'Residenti' => '4050803', 'ResidentiPerc' => '6.8', 'Superficie' => '19371', 'SuperficiePerc' => '6.4', 'Densita' => '209.1', 'Comuni' => '258', 'Province' => '6'),
            array('RegioneID' => '14', 'AreaID' => '5', 'Regione' => 'Sardegna', 'Residenti' => '1640379', 'ResidentiPerc' => '2.7', 'Superficie' => '24089', 'SuperficiePerc' => '8', 'Densita' => '68.1', 'Comuni' => '377', 'Province' => '8'),
            array('RegioneID' => '15', 'AreaID' => '5', 'Regione' => 'Sicilia', 'Residenti' => '4999932', 'ResidentiPerc' => '8.4', 'Superficie' => '25703', 'SuperficiePerc' => '8.5', 'Densita' => '194.5', 'Comuni' => '390', 'Province' => '9'),
            array('RegioneID' => '16', 'AreaID' => '3', 'Regione' => 'Toscana', 'Residenti' => '3692828', 'ResidentiPerc' => '6.2', 'Superficie' => '22990', 'SuperficiePerc' => '7.6', 'Densita' => '160.6', 'Comuni' => '287', 'Province' => '10'),
            array('RegioneID' => '17', 'AreaID' => '2', 'Regione' => 'Trentino-Alto Adige', 'Residenti' => '1039934', 'ResidentiPerc' => '1.7', 'Superficie' => '13607', 'SuperficiePerc' => '4.5', 'Densita' => '76.4', 'Comuni' => '333', 'Province' => '2'),
            array('RegioneID' => '18', 'AreaID' => '3', 'Regione' => 'Umbria', 'Residenti' => '886239', 'ResidentiPerc' => '1.5', 'Superficie' => '8456', 'SuperficiePerc' => '2.8', 'Densita' => '104.8', 'Comuni' => '92', 'Province' => '2'),
            array('RegioneID' => '19', 'AreaID' => '1', 'Regione' => 'Valle d\'Aosta', 'Residenti' => '127844', 'ResidentiPerc' => '0.2', 'Superficie' => '3263', 'SuperficiePerc' => '1.1', 'Densita' => '39.2', 'Comuni' => '74', 'Province' => '1'),
            array('RegioneID' => '20', 'AreaID' => '2', 'Regione' => 'Veneto', 'Residenti' => '4881756', 'ResidentiPerc' => '8.2', 'Superficie' => '18391', 'SuperficiePerc' => '6.1', 'Densita' => '265.4', 'Comuni' => '581', 'Province' => '7'),
        ));
        # province
        $this->createTable('province', array(
            'ProvinciaID' => self::Pk(),
            'RegioneID' => self::TypeInt(true),
            'Provincia' => self::TypeVarchar(50, true),
            'Residenti' => self::TypeInt(true),
            'ResidentiPerc' => self::TypeFloat(true),
            'Superrficie' => self::TypeInt(true),
            'Densita' => self::TypeFloat(true),
            'Comuni' => 'int(3) unsigned NOT NULL',
            'Sigla' => self::TypeVarchar(2, true),
            self::Pk('ProvinciaID'),
            'UNIQUE KEY unique_province_provincia (Provincia)',
            'UNIQUE KEY unique_province_sigla (Sigla)',
                ), self::TableOptions());
        $this->addForeignKey('fk_province_regione', 'province', 'RegioneID', 'regioni');
        $this->insertMultiple('province', array(
            array('ProvinciaID' => '1', 'RegioneID' => '15', 'Provincia' => 'Agrigento', 'Residenti' => '446081', 'ResidentiPerc' => '0.7', 'Superrficie' => '3042', 'Densita' => '146.6', 'Comuni' => '43', 'Sigla' => 'AG'),
            array('ProvinciaID' => '2', 'RegioneID' => '12', 'Provincia' => 'Alessandria', 'Residenti' => '427354', 'ResidentiPerc' => '0.7', 'Superrficie' => '3562', 'Densita' => '120', 'Comuni' => '190', 'Sigla' => 'AL'),
            array('ProvinciaID' => '3', 'RegioneID' => '10', 'Provincia' => 'Ancona', 'Residenti' => '475495', 'ResidentiPerc' => '0.8', 'Superrficie' => '1940', 'Densita' => '245.1', 'Comuni' => '49', 'Sigla' => 'AN'),
            array('ProvinciaID' => '4', 'RegioneID' => '19', 'Provincia' => 'Aosta', 'Residenti' => '127844', 'ResidentiPerc' => '0.2', 'Superrficie' => '3263', 'Densita' => '39.2', 'Comuni' => '74', 'Sigla' => 'AO'),
            array('ProvinciaID' => '5', 'RegioneID' => '16', 'Provincia' => 'Arezzo', 'Residenti' => '344437', 'ResidentiPerc' => '0.6', 'Superrficie' => '3235', 'Densita' => '106.5', 'Comuni' => '39', 'Sigla' => 'AR'),
            array('ProvinciaID' => '6', 'RegioneID' => '10', 'Provincia' => 'Ascoli Piceno', 'Residenti' => '210711', 'ResidentiPerc' => '0.4', 'Superrficie' => '1228', 'Densita' => '171.6', 'Comuni' => '33', 'Sigla' => 'AP'),
            array('ProvinciaID' => '7', 'RegioneID' => '12', 'Provincia' => 'Asti', 'Residenti' => '217978', 'ResidentiPerc' => '0.4', 'Superrficie' => '1511', 'Densita' => '144.3', 'Comuni' => '118', 'Sigla' => 'AT'),
            array('ProvinciaID' => '8', 'RegioneID' => '4', 'Provincia' => 'Avellino', 'Residenti' => '428523', 'ResidentiPerc' => '0.7', 'Superrficie' => '2792', 'Densita' => '153.5', 'Comuni' => '119', 'Sigla' => 'AV'),
            array('ProvinciaID' => '9', 'RegioneID' => '13', 'Provincia' => 'Bari', 'Residenti' => '1246297', 'ResidentiPerc' => '2.1', 'Superrficie' => '3825', 'Densita' => '325.8', 'Comuni' => '41', 'Sigla' => 'BA'),
            array('ProvinciaID' => '10', 'RegioneID' => '13', 'Provincia' => 'Barletta-Andria-Trani', 'Residenti' => '392446', 'ResidentiPerc' => '0.7', 'Superrficie' => '1539', 'Densita' => '255.1', 'Comuni' => '10', 'Sigla' => 'BT'),
            array('ProvinciaID' => '11', 'RegioneID' => '20', 'Provincia' => 'Belluno', 'Residenti' => '209364', 'ResidentiPerc' => '0.4', 'Superrficie' => '3678', 'Densita' => '56.9', 'Comuni' => '69', 'Sigla' => 'BL'),
            array('ProvinciaID' => '12', 'RegioneID' => '4', 'Provincia' => 'Benevento', 'Residenti' => '283651', 'ResidentiPerc' => '0.5', 'Superrficie' => '2071', 'Densita' => '137', 'Comuni' => '78', 'Sigla' => 'BN'),
            array('ProvinciaID' => '13', 'RegioneID' => '9', 'Provincia' => 'Bergamo', 'Residenti' => '1094062', 'ResidentiPerc' => '1.8', 'Superrficie' => '2723', 'Densita' => '401.8', 'Comuni' => '244', 'Sigla' => 'BG'),
            array('ProvinciaID' => '14', 'RegioneID' => '12', 'Provincia' => 'Biella', 'Residenti' => '181426', 'ResidentiPerc' => '0.3', 'Superrficie' => '914', 'Densita' => '198.6', 'Comuni' => '82', 'Sigla' => 'BI'),
            array('ProvinciaID' => '15', 'RegioneID' => '5', 'Provincia' => 'Bologna', 'Residenti' => '990681', 'ResidentiPerc' => '1.7', 'Superrficie' => '3703', 'Densita' => '267.6', 'Comuni' => '60', 'Sigla' => 'BO'),
            array('ProvinciaID' => '16', 'RegioneID' => '17', 'Provincia' => 'Bolzano', 'Residenti' => '509626', 'ResidentiPerc' => '0.9', 'Superrficie' => '7400', 'Densita' => '68.9', 'Comuni' => '116', 'Sigla' => 'BZ'),
            array('ProvinciaID' => '17', 'RegioneID' => '9', 'Provincia' => 'Brescia', 'Residenti' => '1247192', 'ResidentiPerc' => '2.1', 'Superrficie' => '4784', 'Densita' => '260.7', 'Comuni' => '206', 'Sigla' => 'BS'),
            array('ProvinciaID' => '18', 'RegioneID' => '13', 'Provincia' => 'Brindisi', 'Residenti' => '399835', 'ResidentiPerc' => '0.7', 'Superrficie' => '1839', 'Densita' => '217.4', 'Comuni' => '20', 'Sigla' => 'BR'),
            array('ProvinciaID' => '19', 'RegioneID' => '14', 'Provincia' => 'Cagliari', 'Residenti' => '551077', 'ResidentiPerc' => '0.9', 'Superrficie' => '4570', 'Densita' => '120.6', 'Comuni' => '71', 'Sigla' => 'CA'),
            array('ProvinciaID' => '20', 'RegioneID' => '15', 'Provincia' => 'Caltanissetta', 'Residenti' => '272458', 'ResidentiPerc' => '0.5', 'Superrficie' => '2125', 'Densita' => '128.2', 'Comuni' => '22', 'Sigla' => 'CL'),
            array('ProvinciaID' => '21', 'RegioneID' => '11', 'Provincia' => 'Campobasso', 'Residenti' => '226217', 'ResidentiPerc' => '0.4', 'Superrficie' => '2909', 'Densita' => '77.8', 'Comuni' => '84', 'Sigla' => 'CB'),
            array('ProvinciaID' => '22', 'RegioneID' => '14', 'Provincia' => 'Carbonia-Iglesias', 'Residenti' => '127958', 'ResidentiPerc' => '0.2', 'Superrficie' => '1495', 'Densita' => '85.6', 'Comuni' => '23', 'Sigla' => 'CI'),
            array('ProvinciaID' => '23', 'RegioneID' => '4', 'Provincia' => 'Caserta', 'Residenti' => '908784', 'ResidentiPerc' => '1.5', 'Superrficie' => '2639', 'Densita' => '344.3', 'Comuni' => '104', 'Sigla' => 'CE'),
            array('ProvinciaID' => '24', 'RegioneID' => '15', 'Provincia' => 'Catania', 'Residenti' => '1077113', 'ResidentiPerc' => '1.8', 'Superrficie' => '3552', 'Densita' => '303.2', 'Comuni' => '58', 'Sigla' => 'CT'),
            array('ProvinciaID' => '25', 'RegioneID' => '3', 'Provincia' => 'Catanzaro', 'Residenti' => '359716', 'ResidentiPerc' => '0.6', 'Superrficie' => '2391', 'Densita' => '150.4', 'Comuni' => '80', 'Sigla' => 'CZ'),
            array('ProvinciaID' => '26', 'RegioneID' => '1', 'Provincia' => 'Chieti', 'Residenti' => '389053', 'ResidentiPerc' => '0.7', 'Superrficie' => '2588', 'Densita' => '150.3', 'Comuni' => '104', 'Sigla' => 'CH'),
            array('ProvinciaID' => '27', 'RegioneID' => '9', 'Provincia' => 'Como', 'Residenti' => '592504', 'ResidentiPerc' => '1', 'Superrficie' => '1288', 'Densita' => '460', 'Comuni' => '160', 'Sigla' => 'CO'),
            array('ProvinciaID' => '28', 'RegioneID' => '3', 'Provincia' => 'Cosenza', 'Residenti' => '714281', 'ResidentiPerc' => '1.2', 'Superrficie' => '6650', 'Densita' => '107.4', 'Comuni' => '155', 'Sigla' => 'CS'),
            array('ProvinciaID' => '29', 'RegioneID' => '9', 'Provincia' => 'Cremona', 'Residenti' => '361812', 'ResidentiPerc' => '0.6', 'Superrficie' => '1771', 'Densita' => '204.3', 'Comuni' => '115', 'Sigla' => 'CR'),
            array('ProvinciaID' => '30', 'RegioneID' => '3', 'Provincia' => 'Crotone', 'Residenti' => '171666', 'ResidentiPerc' => '0.3', 'Superrficie' => '1717', 'Densita' => '100', 'Comuni' => '27', 'Sigla' => 'KR'),
            array('ProvinciaID' => '31', 'RegioneID' => '12', 'Provincia' => 'Cuneo', 'Residenti' => '589102', 'ResidentiPerc' => '1', 'Superrficie' => '6903', 'Densita' => '85.3', 'Comuni' => '250', 'Sigla' => 'CN'),
            array('ProvinciaID' => '32', 'RegioneID' => '15', 'Provincia' => 'Enna', 'Residenti' => '172413', 'ResidentiPerc' => '0.3', 'Superrficie' => '2562', 'Densita' => '67.3', 'Comuni' => '20', 'Sigla' => 'EN'),
            array('ProvinciaID' => '33', 'RegioneID' => '10', 'Provincia' => 'Fermo', 'Residenti' => '175143', 'ResidentiPerc' => '0.3', 'Superrficie' => '860', 'Densita' => '203.8', 'Comuni' => '40', 'Sigla' => 'FM'),
            array('ProvinciaID' => '34', 'RegioneID' => '5', 'Provincia' => 'Ferrara', 'Residenti' => '352723', 'ResidentiPerc' => '0.6', 'Superrficie' => '2631', 'Densita' => '134.1', 'Comuni' => '26', 'Sigla' => 'FE'),
            array('ProvinciaID' => '35', 'RegioneID' => '16', 'Provincia' => 'Firenze', 'Residenti' => '987354', 'ResidentiPerc' => '1.7', 'Superrficie' => '3514', 'Densita' => '280.9', 'Comuni' => '44', 'Sigla' => 'FI'),
            array('ProvinciaID' => '36', 'RegioneID' => '13', 'Provincia' => 'Foggia', 'Residenti' => '628221', 'ResidentiPerc' => '1.1', 'Superrficie' => '6971', 'Densita' => '90.1', 'Comuni' => '61', 'Sigla' => 'FG'),
            array('ProvinciaID' => '37', 'RegioneID' => '5', 'Provincia' => 'Forlì-Cesena', 'Residenti' => '392817', 'ResidentiPerc' => '0.7', 'Superrficie' => '2377', 'Densita' => '165.3', 'Comuni' => '30', 'Sigla' => 'FC'),
            array('ProvinciaID' => '38', 'RegioneID' => '7', 'Provincia' => 'Frosinone', 'Residenti' => '493229', 'ResidentiPerc' => '0.8', 'Superrficie' => '3244', 'Densita' => '152', 'Comuni' => '91', 'Sigla' => 'FR'),
            array('ProvinciaID' => '39', 'RegioneID' => '8', 'Provincia' => 'Genova', 'Residenti' => '851283', 'ResidentiPerc' => '1.4', 'Superrficie' => '1839', 'Densita' => '462.9', 'Comuni' => '67', 'Sigla' => 'GE'),
            array('ProvinciaID' => '40', 'RegioneID' => '6', 'Provincia' => 'Gorizia', 'Residenti' => '140650', 'ResidentiPerc' => '0.2', 'Superrficie' => '466', 'Densita' => '301.8', 'Comuni' => '25', 'Sigla' => 'GO'),
            array('ProvinciaID' => '41', 'RegioneID' => '16', 'Provincia' => 'Grosseto', 'Residenti' => '220982', 'ResidentiPerc' => '0.4', 'Superrficie' => '4504', 'Densita' => '49.1', 'Comuni' => '28', 'Sigla' => 'GR'),
            array('ProvinciaID' => '42', 'RegioneID' => '8', 'Provincia' => 'Imperia', 'Residenti' => '214290', 'ResidentiPerc' => '0.4', 'Superrficie' => '1156', 'Densita' => '185.4', 'Comuni' => '67', 'Sigla' => 'IM'),
            array('ProvinciaID' => '43', 'RegioneID' => '11', 'Provincia' => 'Isernia', 'Residenti' => '87124', 'ResidentiPerc' => '0.1', 'Superrficie' => '1524', 'Densita' => '57.2', 'Comuni' => '52', 'Sigla' => 'IS'),
            array('ProvinciaID' => '44', 'RegioneID' => '8', 'Provincia' => 'La Spezia', 'Residenti' => '218717', 'ResidentiPerc' => '0.4', 'Superrficie' => '881', 'Densita' => '248.3', 'Comuni' => '32', 'Sigla' => 'SP'),
            array('ProvinciaID' => '45', 'RegioneID' => '1', 'Provincia' => 'L\'Aquila', 'Residenti' => '300774', 'ResidentiPerc' => '0.5', 'Superrficie' => '5034', 'Densita' => '59.7', 'Comuni' => '108', 'Sigla' => 'AQ'),
            array('ProvinciaID' => '46', 'RegioneID' => '7', 'Provincia' => 'Latina', 'Residenti' => '552090', 'ResidentiPerc' => '0.9', 'Superrficie' => '2251', 'Densita' => '245.3', 'Comuni' => '33', 'Sigla' => 'LT'),
            array('ProvinciaID' => '47', 'RegioneID' => '13', 'Provincia' => 'Lecce', 'Residenti' => '801190', 'ResidentiPerc' => '1.3', 'Superrficie' => '2759', 'Densita' => '290.3', 'Comuni' => '97', 'Sigla' => 'LE'),
            array('ProvinciaID' => '48', 'RegioneID' => '9', 'Provincia' => 'Lecco', 'Residenti' => '338425', 'ResidentiPerc' => '0.6', 'Superrficie' => '816', 'Densita' => '414.7', 'Comuni' => '90', 'Sigla' => 'LC'),
            array('ProvinciaID' => '49', 'RegioneID' => '16', 'Provincia' => 'Livorno', 'Residenti' => '335631', 'ResidentiPerc' => '0.6', 'Superrficie' => '1211', 'Densita' => '277.1', 'Comuni' => '20', 'Sigla' => 'LI'),
            array('ProvinciaID' => '50', 'RegioneID' => '9', 'Provincia' => 'Lodi', 'Residenti' => '225798', 'ResidentiPerc' => '0.4', 'Superrficie' => '782', 'Densita' => '288.7', 'Comuni' => '61', 'Sigla' => 'LO'),
            array('ProvinciaID' => '51', 'RegioneID' => '16', 'Provincia' => 'Lucca', 'Residenti' => '388555', 'ResidentiPerc' => '0.7', 'Superrficie' => '1773', 'Densita' => '219.2', 'Comuni' => '35', 'Sigla' => 'LU'),
            array('ProvinciaID' => '52', 'RegioneID' => '10', 'Provincia' => 'Macerata', 'Residenti' => '320418', 'ResidentiPerc' => '0.5', 'Superrficie' => '2774', 'Densita' => '115.5', 'Comuni' => '57', 'Sigla' => 'MC'),
            array('ProvinciaID' => '53', 'RegioneID' => '9', 'Provincia' => 'Mantova', 'Residenti' => '411335', 'ResidentiPerc' => '0.7', 'Superrficie' => '2339', 'Densita' => '175.9', 'Comuni' => '70', 'Sigla' => 'MN'),
            array('ProvinciaID' => '54', 'RegioneID' => '16', 'Provincia' => 'Massa-Carrara', 'Residenti' => '199330', 'ResidentiPerc' => '0.3', 'Superrficie' => '1156', 'Densita' => '172.4', 'Comuni' => '17', 'Sigla' => 'MS'),
            array('ProvinciaID' => '55', 'RegioneID' => '2', 'Provincia' => 'Matera', 'Residenti' => '200012', 'ResidentiPerc' => '0.3', 'Superrficie' => '3446', 'Densita' => '58', 'Comuni' => '31', 'Sigla' => 'MT'),
            array('ProvinciaID' => '56', 'RegioneID' => '15', 'Provincia' => 'Messina', 'Residenti' => '648062', 'ResidentiPerc' => '1.1', 'Superrficie' => '3247', 'Densita' => '199.6', 'Comuni' => '108', 'Sigla' => 'ME'),
            array('ProvinciaID' => '57', 'RegioneID' => '9', 'Provincia' => 'Milano', 'Residenti' => '3075083', 'ResidentiPerc' => '5.2', 'Superrficie' => '1579', 'Densita' => '1947.6', 'Comuni' => '134', 'Sigla' => 'MI'),
            array('ProvinciaID' => '58', 'RegioneID' => '5', 'Provincia' => 'Modena', 'Residenti' => '688376', 'ResidentiPerc' => '1.2', 'Superrficie' => '2689', 'Densita' => '256', 'Comuni' => '47', 'Sigla' => 'MO'),
            array('ProvinciaID' => '59', 'RegioneID' => '9', 'Provincia' => 'Monza e della Brianza', 'Residenti' => '850684', 'ResidentiPerc' => '1.4', 'Superrficie' => '405', 'Densita' => '2097.9', 'Comuni' => '55', 'Sigla' => 'MB'),
            array('ProvinciaID' => '60', 'RegioneID' => '4', 'Provincia' => 'Napoli', 'Residenti' => '3055339', 'ResidentiPerc' => '5.1', 'Superrficie' => '1171', 'Densita' => '2609.7', 'Comuni' => '92', 'Sigla' => 'NA'),
            array('ProvinciaID' => '61', 'RegioneID' => '12', 'Provincia' => 'Novara', 'Residenti' => '367022', 'ResidentiPerc' => '0.6', 'Superrficie' => '1339', 'Densita' => '274.1', 'Comuni' => '88', 'Sigla' => 'NO'),
            array('ProvinciaID' => '62', 'RegioneID' => '14', 'Provincia' => 'Nuoro', 'Residenti' => '158314', 'ResidentiPerc' => '0.3', 'Superrficie' => '3934', 'Densita' => '40.2', 'Comuni' => '52', 'Sigla' => 'NU'),
            array('ProvinciaID' => '63', 'RegioneID' => '14', 'Provincia' => 'Olbia-Tempio', 'Residenti' => '152455', 'ResidentiPerc' => '0.3', 'Superrficie' => '3399', 'Densita' => '44.9', 'Comuni' => '26', 'Sigla' => 'OT'),
            array('ProvinciaID' => '64', 'RegioneID' => '14', 'Provincia' => 'Oristano', 'Residenti' => '163079', 'ResidentiPerc' => '0.3', 'Superrficie' => '3040', 'Densita' => '53.6', 'Comuni' => '88', 'Sigla' => 'OR'),
            array('ProvinciaID' => '65', 'RegioneID' => '20', 'Provincia' => 'Padova', 'Residenti' => '927848', 'ResidentiPerc' => '1.6', 'Superrficie' => '2142', 'Densita' => '433.3', 'Comuni' => '104', 'Sigla' => 'PD'),
            array('ProvinciaID' => '66', 'RegioneID' => '15', 'Provincia' => 'Palermo', 'Residenti' => '1243638', 'ResidentiPerc' => '2.1', 'Superrficie' => '4992', 'Densita' => '249.1', 'Comuni' => '82', 'Sigla' => 'PA'),
            array('ProvinciaID' => '67', 'RegioneID' => '5', 'Provincia' => 'Parma', 'Residenti' => '431049', 'ResidentiPerc' => '0.7', 'Superrficie' => '3449', 'Densita' => '125', 'Comuni' => '47', 'Sigla' => 'PR'),
            array('ProvinciaID' => '68', 'RegioneID' => '9', 'Provincia' => 'Pavia', 'Residenti' => '539569', 'ResidentiPerc' => '0.9', 'Superrficie' => '2965', 'Densita' => '182', 'Comuni' => '190', 'Sigla' => 'PV'),
            array('ProvinciaID' => '69', 'RegioneID' => '18', 'Provincia' => 'Perugia', 'Residenti' => '657873', 'ResidentiPerc' => '1.1', 'Superrficie' => '6334', 'Densita' => '103.9', 'Comuni' => '59', 'Sigla' => 'PG'),
            array('ProvinciaID' => '70', 'RegioneID' => '10', 'Provincia' => 'Pesaro e Urbino', 'Residenti' => '363388', 'ResidentiPerc' => '0.6', 'Superrficie' => '2564', 'Densita' => '141.7', 'Comuni' => '60', 'Sigla' => 'PU'),
            array('ProvinciaID' => '71', 'RegioneID' => '1', 'Provincia' => 'Pescara', 'Residenti' => '315725', 'ResidentiPerc' => '0.5', 'Superrficie' => '1225', 'Densita' => '257.8', 'Comuni' => '46', 'Sigla' => 'PE'),
            array('ProvinciaID' => '72', 'RegioneID' => '5', 'Provincia' => 'Piacenza', 'Residenti' => '286336', 'ResidentiPerc' => '0.5', 'Superrficie' => '2589', 'Densita' => '110.6', 'Comuni' => '48', 'Sigla' => 'PC'),
            array('ProvinciaID' => '73', 'RegioneID' => '16', 'Provincia' => 'Pisa', 'Residenti' => '413602', 'ResidentiPerc' => '0.7', 'Superrficie' => '2444', 'Densita' => '169.2', 'Comuni' => '39', 'Sigla' => 'PI'),
            array('ProvinciaID' => '74', 'RegioneID' => '16', 'Provincia' => 'Pistoia', 'Residenti' => '287445', 'ResidentiPerc' => '0.5', 'Superrficie' => '965', 'Densita' => '297.9', 'Comuni' => '22', 'Sigla' => 'PT'),
            array('ProvinciaID' => '75', 'RegioneID' => '6', 'Provincia' => 'Pordenone', 'Residenti' => '312911', 'ResidentiPerc' => '0.5', 'Superrficie' => '2273', 'Densita' => '137.7', 'Comuni' => '51', 'Sigla' => 'PN'),
            array('ProvinciaID' => '76', 'RegioneID' => '2', 'Provincia' => 'Potenza', 'Residenti' => '376182', 'ResidentiPerc' => '0.6', 'Superrficie' => '6548', 'Densita' => '57.4', 'Comuni' => '100', 'Sigla' => 'PZ'),
            array('ProvinciaID' => '77', 'RegioneID' => '16', 'Provincia' => 'Prato', 'Residenti' => '248292', 'ResidentiPerc' => '0.4', 'Superrficie' => '365', 'Densita' => '679.8', 'Comuni' => '7', 'Sigla' => 'PO'),
            array('ProvinciaID' => '78', 'RegioneID' => '15', 'Provincia' => 'Ragusa', 'Residenti' => '310220', 'ResidentiPerc' => '0.5', 'Superrficie' => '1614', 'Densita' => '192.2', 'Comuni' => '12', 'Sigla' => 'RG'),
            array('ProvinciaID' => '79', 'RegioneID' => '5', 'Provincia' => 'Ravenna', 'Residenti' => '386111', 'ResidentiPerc' => '0.6', 'Superrficie' => '1858', 'Densita' => '207.8', 'Comuni' => '18', 'Sigla' => 'RA'),
            array('ProvinciaID' => '80', 'RegioneID' => '3', 'Provincia' => 'Reggio Calabria', 'Residenti' => '550323', 'ResidentiPerc' => '0.9', 'Superrficie' => '3183', 'Densita' => '172.9', 'Comuni' => '97', 'Sigla' => 'RC'),
            array('ProvinciaID' => '81', 'RegioneID' => '5', 'Provincia' => 'Reggio Emilia', 'Residenti' => '522468', 'ResidentiPerc' => '0.9', 'Superrficie' => '2293', 'Densita' => '227.9', 'Comuni' => '45', 'Sigla' => 'RE'),
            array('ProvinciaID' => '82', 'RegioneID' => '7', 'Provincia' => 'Rieti', 'Residenti' => '156521', 'ResidentiPerc' => '0.3', 'Superrficie' => '2749', 'Densita' => '56.9', 'Comuni' => '73', 'Sigla' => 'RI'),
            array('ProvinciaID' => '83', 'RegioneID' => '5', 'Provincia' => 'Rimini', 'Residenti' => '326926', 'ResidentiPerc' => '0.5', 'Superrficie' => '867', 'Densita' => '377', 'Comuni' => '27', 'Sigla' => 'RN'),
            array('ProvinciaID' => '84', 'RegioneID' => '7', 'Provincia' => 'Roma', 'Residenti' => '4039813', 'ResidentiPerc' => '6.8', 'Superrficie' => '5352', 'Densita' => '754.8', 'Comuni' => '121', 'Sigla' => 'RM'),
            array('ProvinciaID' => '85', 'RegioneID' => '20', 'Provincia' => 'Rovigo', 'Residenti' => '242543', 'ResidentiPerc' => '0.4', 'Superrficie' => '1790', 'Densita' => '135.5', 'Comuni' => '50', 'Sigla' => 'RO'),
            array('ProvinciaID' => '86', 'RegioneID' => '4', 'Provincia' => 'Salerno', 'Residenti' => '1093453', 'ResidentiPerc' => '1.8', 'Superrficie' => '4917', 'Densita' => '222.4', 'Comuni' => '158', 'Sigla' => 'SA'),
            array('ProvinciaID' => '87', 'RegioneID' => '14', 'Provincia' => 'Medio Campidano', 'Residenti' => '100624', 'ResidentiPerc' => '0.2', 'Superrficie' => '1516', 'Densita' => '66.4', 'Comuni' => '28', 'Sigla' => 'VS'),
            array('ProvinciaID' => '88', 'RegioneID' => '14', 'Provincia' => 'Sassari', 'Residenti' => '329551', 'ResidentiPerc' => '0.6', 'Superrficie' => '4282', 'Densita' => '77', 'Comuni' => '66', 'Sigla' => 'SS'),
            array('ProvinciaID' => '89', 'RegioneID' => '8', 'Provincia' => 'Savona', 'Residenti' => '280837', 'ResidentiPerc' => '0.5', 'Superrficie' => '1545', 'Densita' => '181.8', 'Comuni' => '69', 'Sigla' => 'SV'),
            array('ProvinciaID' => '90', 'RegioneID' => '16', 'Provincia' => 'Siena', 'Residenti' => '267200', 'ResidentiPerc' => '0.4', 'Superrficie' => '3821', 'Densita' => '69.9', 'Comuni' => '36', 'Sigla' => 'SI'),
            array('ProvinciaID' => '91', 'RegioneID' => '15', 'Provincia' => 'Siracusa', 'Residenti' => '399469', 'ResidentiPerc' => '0.7', 'Superrficie' => '2109', 'Densita' => '189.4', 'Comuni' => '21', 'Sigla' => 'SR'),
            array('ProvinciaID' => '92', 'RegioneID' => '9', 'Provincia' => 'Sondrio', 'Residenti' => '181101', 'ResidentiPerc' => '0.3', 'Superrficie' => '3212', 'Densita' => '56.4', 'Comuni' => '78', 'Sigla' => 'SO'),
            array('ProvinciaID' => '93', 'RegioneID' => '13', 'Provincia' => 'Taranto', 'Residenti' => '582814', 'ResidentiPerc' => '1', 'Superrficie' => '2437', 'Densita' => '239.2', 'Comuni' => '29', 'Sigla' => 'TA'),
            array('ProvinciaID' => '94', 'RegioneID' => '1', 'Provincia' => 'Teramo', 'Residenti' => '306955', 'ResidentiPerc' => '0.5', 'Superrficie' => '1948', 'Densita' => '157.6', 'Comuni' => '47', 'Sigla' => 'TE'),
            array('ProvinciaID' => '95', 'RegioneID' => '18', 'Provincia' => 'Terni', 'Residenti' => '228366', 'ResidentiPerc' => '0.4', 'Superrficie' => '2122', 'Densita' => '107.6', 'Comuni' => '33', 'Sigla' => 'TR'),
            array('ProvinciaID' => '96', 'RegioneID' => '12', 'Provincia' => 'Torino', 'Residenti' => '2254720', 'ResidentiPerc' => '3.8', 'Superrficie' => '6830', 'Densita' => '330.1', 'Comuni' => '315', 'Sigla' => 'TO'),
            array('ProvinciaID' => '97', 'RegioneID' => '14', 'Provincia' => 'Ogliastra', 'Residenti' => '57321', 'ResidentiPerc' => '0.1', 'Superrficie' => '1854', 'Densita' => '30.9', 'Comuni' => '23', 'Sigla' => 'OG'),
            array('ProvinciaID' => '98', 'RegioneID' => '15', 'Provincia' => 'Trapani', 'Residenti' => '430478', 'ResidentiPerc' => '0.7', 'Superrficie' => '2460', 'Densita' => '175', 'Comuni' => '24', 'Sigla' => 'TP'),
            array('ProvinciaID' => '99', 'RegioneID' => '17', 'Provincia' => 'Trento', 'Residenti' => '530308', 'ResidentiPerc' => '0.9', 'Superrficie' => '6207', 'Densita' => '85.4', 'Comuni' => '217', 'Sigla' => 'TN'),
            array('ProvinciaID' => '100', 'RegioneID' => '20', 'Provincia' => 'Treviso', 'Residenti' => '881245', 'ResidentiPerc' => '1.5', 'Superrficie' => '2477', 'Densita' => '355.8', 'Comuni' => '95', 'Sigla' => 'TV'),
            array('ProvinciaID' => '101', 'RegioneID' => '6', 'Provincia' => 'Trieste', 'Residenti' => '231677', 'ResidentiPerc' => '0.4', 'Superrficie' => '212', 'Densita' => '1093.7', 'Comuni' => '6', 'Sigla' => 'TS'),
            array('ProvinciaID' => '102', 'RegioneID' => '6', 'Provincia' => 'Udine', 'Residenti' => '536622', 'ResidentiPerc' => '0.9', 'Superrficie' => '4904', 'Densita' => '109.4', 'Comuni' => '136', 'Sigla' => 'UD'),
            array('ProvinciaID' => '103', 'RegioneID' => '9', 'Provincia' => 'Varese', 'Residenti' => '876960', 'ResidentiPerc' => '1.5', 'Superrficie' => '1199', 'Densita' => '731.6', 'Comuni' => '141', 'Sigla' => 'VA'),
            array('ProvinciaID' => '104', 'RegioneID' => '20', 'Provincia' => 'Venezia', 'Residenti' => '847983', 'ResidentiPerc' => '1.4', 'Superrficie' => '2462', 'Densita' => '344.5', 'Comuni' => '44', 'Sigla' => 'VE'),
            array('ProvinciaID' => '105', 'RegioneID' => '12', 'Provincia' => 'Verbano-Cusio-Ossola', 'Residenti' => '160143', 'ResidentiPerc' => '0.3', 'Superrficie' => '2255', 'Densita' => '71', 'Comuni' => '77', 'Sigla' => 'VB'),
            array('ProvinciaID' => '106', 'RegioneID' => '12', 'Provincia' => 'Vercelli', 'Residenti' => '176307', 'ResidentiPerc' => '0.3', 'Superrficie' => '2088', 'Densita' => '84.4', 'Comuni' => '86', 'Sigla' => 'VC'),
            array('ProvinciaID' => '107', 'RegioneID' => '20', 'Provincia' => 'Verona', 'Residenti' => '907352', 'ResidentiPerc' => '1.5', 'Superrficie' => '3121', 'Densita' => '290.7', 'Comuni' => '98', 'Sigla' => 'VR'),
            array('ProvinciaID' => '108', 'RegioneID' => '3', 'Provincia' => 'Vibo Valentia', 'Residenti' => '162252', 'ResidentiPerc' => '0.3', 'Superrficie' => '1139', 'Densita' => '142.4', 'Comuni' => '50', 'Sigla' => 'VV'),
            array('ProvinciaID' => '109', 'RegioneID' => '20', 'Provincia' => 'Vicenza', 'Residenti' => '865421', 'ResidentiPerc' => '1.4', 'Superrficie' => '2723', 'Densita' => '317.8', 'Comuni' => '121', 'Sigla' => 'VI'),
            array('ProvinciaID' => '110', 'RegioneID' => '7', 'Provincia' => 'Viterbo', 'Residenti' => '315623', 'ResidentiPerc' => '0.5', 'Superrficie' => '3612', 'Densita' => '87.4', 'Comuni' => '60', 'Sigla' => 'VT'),
        ));
        # nazioni
        $this->createTable('nazioni', array(
            'NazioneID' => self::Pk(),
            'NazioneIt' => self::TypeVarchar(255, true),
            'NazioneEn' => self::TypeVarchar(255),
            self::Pk('NazioneID'),
            'UNIQUE KEY unique_nazioni_nazioneit (NazioneIt)',
            'UNIQUE KEY unique_nazioni_nazioneen (NazioneEn)',
                ), self::TableOptions());
        $this->insertMultiple('nazioni', array(
            array('NazioneID' => '1', 'NazioneIt' => 'Afghanistan', 'NazioneEn' => 'Afghanistan'),
            array('NazioneID' => '2', 'NazioneIt' => 'Albania', 'NazioneEn' => 'Albania'),
            array('NazioneID' => '3', 'NazioneIt' => 'Algeria', 'NazioneEn' => 'Algeria'),
            array('NazioneID' => '4', 'NazioneIt' => 'Samoa Americane', 'NazioneEn' => 'American Samoa'),
            array('NazioneID' => '5', 'NazioneIt' => 'Andorra', 'NazioneEn' => 'Andorra'),
            array('NazioneID' => '6', 'NazioneIt' => 'Angola', 'NazioneEn' => 'Angola'),
            array('NazioneID' => '7', 'NazioneIt' => 'Anguilla', 'NazioneEn' => 'Anguilla'),
            array('NazioneID' => '8', 'NazioneIt' => 'Antartide', 'NazioneEn' => 'Antarctica'),
            array('NazioneID' => '9', 'NazioneIt' => 'Antigua e Barbuda', 'NazioneEn' => 'Antigua and Barbuda'),
            array('NazioneID' => '10', 'NazioneIt' => 'Argentina', 'NazioneEn' => 'Argentina'),
            array('NazioneID' => '11', 'NazioneIt' => 'Armenia', 'NazioneEn' => 'Armenia'),
            array('NazioneID' => '12', 'NazioneIt' => 'Aruba', 'NazioneEn' => 'Aruba'),
            array('NazioneID' => '13', 'NazioneIt' => 'Australia', 'NazioneEn' => 'Australia'),
            array('NazioneID' => '14', 'NazioneIt' => 'Austria', 'NazioneEn' => 'Austria'),
            array('NazioneID' => '15', 'NazioneIt' => 'Azerbaijan', 'NazioneEn' => 'Azerbaijan'),
            array('NazioneID' => '16', 'NazioneIt' => 'Bahamas', 'NazioneEn' => 'Bahamas'),
            array('NazioneID' => '17', 'NazioneIt' => 'Bahrain', 'NazioneEn' => 'Bahrain'),
            array('NazioneID' => '18', 'NazioneIt' => 'Bangladesh', 'NazioneEn' => 'Bangladesh'),
            array('NazioneID' => '19', 'NazioneIt' => 'Barbados', 'NazioneEn' => 'Barbados'),
            array('NazioneID' => '20', 'NazioneIt' => 'Bielorussia', 'NazioneEn' => 'Belarus'),
            array('NazioneID' => '21', 'NazioneIt' => 'Belgio', 'NazioneEn' => 'Belgium'),
            array('NazioneID' => '22', 'NazioneIt' => 'Belize', 'NazioneEn' => 'Belize'),
            array('NazioneID' => '23', 'NazioneIt' => 'Benin', 'NazioneEn' => 'Benin'),
            array('NazioneID' => '24', 'NazioneIt' => 'Bermuda', 'NazioneEn' => 'Bermuda'),
            array('NazioneID' => '25', 'NazioneIt' => 'Bhutan', 'NazioneEn' => 'Bhutan'),
            array('NazioneID' => '26', 'NazioneIt' => 'Bolivia', 'NazioneEn' => 'Bolivia'),
            array('NazioneID' => '27', 'NazioneIt' => 'Bosnia ed Erzegovina', 'NazioneEn' => 'Bosnia And Herzegowina'),
            array('NazioneID' => '28', 'NazioneIt' => 'Botswana', 'NazioneEn' => 'Botswana'),
            array('NazioneID' => '29', 'NazioneIt' => 'Isola Bouvet', 'NazioneEn' => 'Bouvet Island'),
            array('NazioneID' => '30', 'NazioneIt' => 'Brasile', 'NazioneEn' => 'Brazil'),
            array('NazioneID' => '31', 'NazioneIt' => 'Territorio Britannico dell\'Oceano Indiano', 'NazioneEn' => 'British Indian Ocean Territory'),
            array('NazioneID' => '32', 'NazioneIt' => 'Stato del Brunei', 'NazioneEn' => 'Brunei Darussalam'),
            array('NazioneID' => '33', 'NazioneIt' => 'Bulgaria', 'NazioneEn' => 'Bulgaria'),
            array('NazioneID' => '34', 'NazioneIt' => 'Burkina Faso', 'NazioneEn' => 'Burkina Faso'),
            array('NazioneID' => '35', 'NazioneIt' => 'Burundi', 'NazioneEn' => 'Burundi'),
            array('NazioneID' => '36', 'NazioneIt' => 'C.A.R.', 'NazioneEn' => 'C.A.R.'),
            array('NazioneID' => '37', 'NazioneIt' => 'Cambogia', 'NazioneEn' => 'Cambodia'),
            array('NazioneID' => '38', 'NazioneIt' => 'Camerun', 'NazioneEn' => 'Cameroon'),
            array('NazioneID' => '39', 'NazioneIt' => 'Canada', 'NazioneEn' => 'Canada'),
            array('NazioneID' => '40', 'NazioneIt' => 'Capo Verde', 'NazioneEn' => 'Cape Verde'),
            array('NazioneID' => '41', 'NazioneIt' => 'Isole Cayman', 'NazioneEn' => 'Cayman Islands'),
            array('NazioneID' => '42', 'NazioneIt' => 'Repubblica Centrafricana', 'NazioneEn' => 'Central African Republic'),
            array('NazioneID' => '43', 'NazioneIt' => 'Ciad', 'NazioneEn' => 'Chad'),
            array('NazioneID' => '44', 'NazioneIt' => 'Cile', 'NazioneEn' => 'Chile'),
            array('NazioneID' => '45', 'NazioneIt' => 'Cina', 'NazioneEn' => 'China'),
            array('NazioneID' => '46', 'NazioneIt' => 'Isola del Natale', 'NazioneEn' => 'Christmas Island'),
            array('NazioneID' => '47', 'NazioneIt' => 'Isole Cocos (Keeling)', 'NazioneEn' => 'Cocos (Keeling) Islands'),
            array('NazioneID' => '48', 'NazioneIt' => 'Colombia', 'NazioneEn' => 'Colombia'),
            array('NazioneID' => '49', 'NazioneIt' => 'Comore', 'NazioneEn' => 'Comoros'),
            array('NazioneID' => '50', 'NazioneIt' => 'Congo', 'NazioneEn' => 'Congo'),
            array('NazioneID' => '51', 'NazioneIt' => 'Isola Cook', 'NazioneEn' => 'Cook Islands'),
            array('NazioneID' => '52', 'NazioneIt' => 'Costa Rica', 'NazioneEn' => 'Costa Rica'),
            array('NazioneID' => '53', 'NazioneIt' => 'Costa d\'Avorio', 'NazioneEn' => 'Cote D\'Ivoire'),
            array('NazioneID' => '54', 'NazioneIt' => 'Croazia', 'NazioneEn' => 'Croatia'),
            array('NazioneID' => '55', 'NazioneIt' => 'Cuba', 'NazioneEn' => 'Cuba'),
            array('NazioneID' => '56', 'NazioneIt' => 'Cipro', 'NazioneEn' => 'Cyprus'),
            array('NazioneID' => '57', 'NazioneIt' => 'Repubblica Ceca', 'NazioneEn' => 'Czech Republic'),
            array('NazioneID' => '58', 'NazioneIt' => 'Danimarca', 'NazioneEn' => 'Denmark'),
            array('NazioneID' => '59', 'NazioneIt' => 'Gibuti', 'NazioneEn' => 'Djibouti'),
            array('NazioneID' => '60', 'NazioneIt' => 'Dominica', 'NazioneEn' => 'Dominica'),
            array('NazioneID' => '61', 'NazioneIt' => 'Repubblica Dominicana', 'NazioneEn' => 'Dominican Republic'),
            array('NazioneID' => '62', 'NazioneIt' => 'Timor Est', 'NazioneEn' => 'East Timor'),
            array('NazioneID' => '63', 'NazioneIt' => 'Ecuador', 'NazioneEn' => 'Ecuador'),
            array('NazioneID' => '64', 'NazioneIt' => 'Egitto', 'NazioneEn' => 'Egypt'),
            array('NazioneID' => '65', 'NazioneIt' => 'El Salvador', 'NazioneEn' => 'El Salvador'),
            array('NazioneID' => '66', 'NazioneIt' => 'Inghilterra', 'NazioneEn' => 'England'),
            array('NazioneID' => '67', 'NazioneIt' => 'Guinea Equatoriale', 'NazioneEn' => 'Equatorial Guinea'),
            array('NazioneID' => '68', 'NazioneIt' => 'Eritrea', 'NazioneEn' => 'Eritrea'),
            array('NazioneID' => '69', 'NazioneIt' => 'Estonia', 'NazioneEn' => 'Estonia'),
            array('NazioneID' => '70', 'NazioneIt' => 'Etiopia', 'NazioneEn' => 'Ethiopia'),
            array('NazioneID' => '71', 'NazioneIt' => 'Isole Falkland (Malvinas)', 'NazioneEn' => 'Falkland Islands (Malvinas)'),
            array('NazioneID' => '72', 'NazioneIt' => 'Faroe', 'NazioneEn' => 'Faroe Islands'),
            array('NazioneID' => '73', 'NazioneIt' => 'Fiji', 'NazioneEn' => 'Fiji'),
            array('NazioneID' => '74', 'NazioneIt' => 'Finlandia', 'NazioneEn' => 'Finland'),
            array('NazioneID' => '75', 'NazioneIt' => 'Francia', 'NazioneEn' => 'France'),
            array('NazioneID' => '76', 'NazioneIt' => 'Guyana Francese', 'NazioneEn' => 'French Guiana'),
            array('NazioneID' => '77', 'NazioneIt' => 'Polinesia Francese', 'NazioneEn' => 'French Polynesia'),
            array('NazioneID' => '78', 'NazioneIt' => 'Terre Australi e Antartiche Francesi', 'NazioneEn' => 'French Southern Territories'),
            array('NazioneID' => '79', 'NazioneIt' => 'Gabon', 'NazioneEn' => 'Gabon'),
            array('NazioneID' => '80', 'NazioneIt' => 'Gambia', 'NazioneEn' => 'Gambia'),
            array('NazioneID' => '81', 'NazioneIt' => 'Georgia', 'NazioneEn' => 'Georgia'),
            array('NazioneID' => '82', 'NazioneIt' => 'Germania', 'NazioneEn' => 'Germany'),
            array('NazioneID' => '83', 'NazioneIt' => 'Ghana', 'NazioneEn' => 'Ghana'),
            array('NazioneID' => '84', 'NazioneIt' => 'Gibilterra', 'NazioneEn' => 'Gibraltar'),
            array('NazioneID' => '85', 'NazioneIt' => 'Grecia', 'NazioneEn' => 'Greece'),
            array('NazioneID' => '86', 'NazioneIt' => 'Groenlandia', 'NazioneEn' => 'Greenland'),
            array('NazioneID' => '87', 'NazioneIt' => 'Grenada', 'NazioneEn' => 'Grenada'),
            array('NazioneID' => '88', 'NazioneIt' => 'Guadalupe', 'NazioneEn' => 'Guadeloupe'),
            array('NazioneID' => '89', 'NazioneIt' => 'Guam', 'NazioneEn' => 'Guam'),
            array('NazioneID' => '90', 'NazioneIt' => 'Guatemala', 'NazioneEn' => 'Guantemala'),
            array('NazioneID' => '91', 'NazioneIt' => 'Guinea', 'NazioneEn' => 'Guinea'),
            array('NazioneID' => '92', 'NazioneIt' => 'Guinea-Bissau', 'NazioneEn' => 'Guinea-Bissau'),
            array('NazioneID' => '93', 'NazioneIt' => 'Guyana', 'NazioneEn' => 'Guyana'),
            array('NazioneID' => '94', 'NazioneIt' => 'Haiti', 'NazioneEn' => 'Haiti'),
            array('NazioneID' => '95', 'NazioneIt' => 'Isole Heard e Mc Donald', 'NazioneEn' => 'Heard And Mc Donald Islands'),
            array('NazioneID' => '96', 'NazioneIt' => 'Honduras', 'NazioneEn' => 'Honduras'),
            array('NazioneID' => '97', 'NazioneIt' => 'Hong Kong', 'NazioneEn' => 'Hong Kong'),
            array('NazioneID' => '98', 'NazioneIt' => 'Ungheria', 'NazioneEn' => 'Hungary'),
            array('NazioneID' => '99', 'NazioneIt' => 'Islanda', 'NazioneEn' => 'Iceland'),
            array('NazioneID' => '100', 'NazioneIt' => 'India', 'NazioneEn' => 'India'),
            array('NazioneID' => '101', 'NazioneIt' => 'Indonesia', 'NazioneEn' => 'Indonesia'),
            array('NazioneID' => '102', 'NazioneIt' => 'Iran', 'NazioneEn' => 'Iran'),
            array('NazioneID' => '103', 'NazioneIt' => 'Iraq', 'NazioneEn' => 'Iraq'),
            array('NazioneID' => '104', 'NazioneIt' => 'Irlanda', 'NazioneEn' => 'Ireland'),
            array('NazioneID' => '105', 'NazioneIt' => 'Israele', 'NazioneEn' => 'Israel'),
            array('NazioneID' => '106', 'NazioneIt' => 'Italia', 'NazioneEn' => 'Italy'),
            array('NazioneID' => '107', 'NazioneIt' => 'Giamaica', 'NazioneEn' => 'Jamaica'),
            array('NazioneID' => '108', 'NazioneIt' => 'Giappone', 'NazioneEn' => 'Japan'),
            array('NazioneID' => '109', 'NazioneIt' => 'Giordania', 'NazioneEn' => 'Jordan'),
            array('NazioneID' => '110', 'NazioneIt' => 'Kazakistan', 'NazioneEn' => 'Kazakhstan'),
            array('NazioneID' => '111', 'NazioneIt' => 'Kenya', 'NazioneEn' => 'Kenya'),
            array('NazioneID' => '112', 'NazioneIt' => 'Kiribati', 'NazioneEn' => 'Kiribati'),
            array('NazioneID' => '113', 'NazioneIt' => 'Corea del Nord', 'NazioneEn' => 'Korea, Democratic People\'s Republic of'),
            array('NazioneID' => '114', 'NazioneIt' => 'Corea del Sud', 'NazioneEn' => 'Korea, Republic of'),
            array('NazioneID' => '115', 'NazioneIt' => 'Kuwait', 'NazioneEn' => 'Kuwait'),
            array('NazioneID' => '116', 'NazioneIt' => 'Kirghizistan', 'NazioneEn' => 'Kyrgyzstan'),
            array('NazioneID' => '117', 'NazioneIt' => 'Laos', 'NazioneEn' => 'Lao People\'s Democratic Republic'),
            array('NazioneID' => '118', 'NazioneIt' => 'Lettonia', 'NazioneEn' => 'Latvia'),
            array('NazioneID' => '119', 'NazioneIt' => 'Libano', 'NazioneEn' => 'Lebanon'),
            array('NazioneID' => '120', 'NazioneIt' => 'Lesotho', 'NazioneEn' => 'Lesotho'),
            array('NazioneID' => '121', 'NazioneIt' => 'Liberia', 'NazioneEn' => 'Liberia'),
            array('NazioneID' => '122', 'NazioneIt' => 'Libia', 'NazioneEn' => 'Libya'),
            array('NazioneID' => '124', 'NazioneIt' => 'Liechtenstein', 'NazioneEn' => 'Liechtenstein'),
            array('NazioneID' => '125', 'NazioneIt' => 'Lituania', 'NazioneEn' => 'Lithuania'),
            array('NazioneID' => '126', 'NazioneIt' => 'Lussenburgo', 'NazioneEn' => 'Luxembourg'),
            array('NazioneID' => '127', 'NazioneIt' => 'Macao', 'NazioneEn' => 'Macau'),
            array('NazioneID' => '128', 'NazioneIt' => 'Macedonia', 'NazioneEn' => 'Macedonia, The Former Yugoslav Republic'),
            array('NazioneID' => '129', 'NazioneIt' => 'Madagascar', 'NazioneEn' => 'Madagascar'),
            array('NazioneID' => '130', 'NazioneIt' => 'Malawi', 'NazioneEn' => 'Malawi'),
            array('NazioneID' => '131', 'NazioneIt' => 'Malesia', 'NazioneEn' => 'Malaysia'),
            array('NazioneID' => '132', 'NazioneIt' => 'Maldive', 'NazioneEn' => 'Maldives'),
            array('NazioneID' => '133', 'NazioneIt' => 'Mali', 'NazioneEn' => 'Mali'),
            array('NazioneID' => '134', 'NazioneIt' => 'Malta', 'NazioneEn' => 'Malta'),
            array('NazioneID' => '135', 'NazioneIt' => 'Isole Marshall', 'NazioneEn' => 'Marshall Islands'),
            array('NazioneID' => '136', 'NazioneIt' => 'Martinica', 'NazioneEn' => 'Martinique'),
            array('NazioneID' => '137', 'NazioneIt' => 'Mauritania', 'NazioneEn' => 'Mauritania'),
            array('NazioneID' => '138', 'NazioneIt' => 'Mauritius', 'NazioneEn' => 'Mauritius'),
            array('NazioneID' => '139', 'NazioneIt' => 'Mayotte', 'NazioneEn' => 'Mayotte'),
            array('NazioneID' => '140', 'NazioneIt' => 'Messico', 'NazioneEn' => 'Mexico'),
            array('NazioneID' => '141', 'NazioneIt' => 'Micronesia (Stati Federati della)', 'NazioneEn' => 'Micronesia (Federated States Of)'),
            array('NazioneID' => '142', 'NazioneIt' => 'Moldavia', 'NazioneEn' => 'Moldova, Republic Of'),
            array('NazioneID' => '143', 'NazioneIt' => 'Monaco', 'NazioneEn' => 'Monaco'),
            array('NazioneID' => '144', 'NazioneIt' => 'Mongolia', 'NazioneEn' => 'Mongolia'),
            array('NazioneID' => '145', 'NazioneIt' => 'Montserrat', 'NazioneEn' => 'Montserrat'),
            array('NazioneID' => '146', 'NazioneIt' => 'Marocco', 'NazioneEn' => 'Morocco'),
            array('NazioneID' => '147', 'NazioneIt' => 'Mozambico', 'NazioneEn' => 'Mozambique'),
            array('NazioneID' => '148', 'NazioneIt' => 'Birmania', 'NazioneEn' => 'Myanmar'),
            array('NazioneID' => '149', 'NazioneIt' => 'Namibia', 'NazioneEn' => 'Namibia'),
            array('NazioneID' => '150', 'NazioneIt' => 'Nauru', 'NazioneEn' => 'Nauru'),
            array('NazioneID' => '151', 'NazioneIt' => 'Nepal', 'NazioneEn' => 'Nepal'),
            array('NazioneID' => '152', 'NazioneIt' => 'Olanda', 'NazioneEn' => 'Netherlands'),
            array('NazioneID' => '153', 'NazioneIt' => 'Antille Olandesi', 'NazioneEn' => 'Netherlands Antilles'),
            array('NazioneID' => '154', 'NazioneIt' => 'Nuova Caledonia', 'NazioneEn' => 'New Caledonia'),
            array('NazioneID' => '155', 'NazioneIt' => 'Nuova Zelanda', 'NazioneEn' => 'New Zealand'),
            array('NazioneID' => '156', 'NazioneIt' => 'Nicaragua', 'NazioneEn' => 'Nicaragua'),
            array('NazioneID' => '157', 'NazioneIt' => 'Niger', 'NazioneEn' => 'Niger'),
            array('NazioneID' => '158', 'NazioneIt' => 'Nigeria', 'NazioneEn' => 'Nigeria'),
            array('NazioneID' => '159', 'NazioneIt' => 'Niue', 'NazioneEn' => 'Niue'),
            array('NazioneID' => '160', 'NazioneIt' => 'Isola Norfolk', 'NazioneEn' => 'Norfolk Island'),
            array('NazioneID' => '162', 'NazioneIt' => 'Irlanda del Nord', 'NazioneEn' => 'Northern Ireland'),
            array('NazioneID' => '163', 'NazioneIt' => 'Isole Marianne Settentrionali', 'NazioneEn' => 'Northern Mariana Islands'),
            array('NazioneID' => '164', 'NazioneIt' => 'Norvegia', 'NazioneEn' => 'Norway'),
            array('NazioneID' => '165', 'NazioneIt' => 'Oman', 'NazioneEn' => 'Oman'),
            array('NazioneID' => '166', 'NazioneIt' => 'Pakistan', 'NazioneEn' => 'Pakistan'),
            array('NazioneID' => '167', 'NazioneIt' => 'Palau', 'NazioneEn' => 'Palau'),
            array('NazioneID' => '168', 'NazioneIt' => 'Panama', 'NazioneEn' => 'Panama'),
            array('NazioneID' => '169', 'NazioneIt' => 'Papua Nuova Guinea', 'NazioneEn' => 'Papua New Guinea'),
            array('NazioneID' => '170', 'NazioneIt' => 'Paraguay', 'NazioneEn' => 'Paraguay'),
            array('NazioneID' => '171', 'NazioneIt' => 'Peru', 'NazioneEn' => 'Peru'),
            array('NazioneID' => '172', 'NazioneIt' => 'Filippine', 'NazioneEn' => 'Philippines'),
            array('NazioneID' => '173', 'NazioneIt' => 'Pitcairn', 'NazioneEn' => 'Pitcairn'),
            array('NazioneID' => '174', 'NazioneIt' => 'Polonia', 'NazioneEn' => 'Poland'),
            array('NazioneID' => '175', 'NazioneIt' => 'Portogallo', 'NazioneEn' => 'Portugal'),
            array('NazioneID' => '176', 'NazioneIt' => 'Porto Rico', 'NazioneEn' => 'Puerto Rico'),
            array('NazioneID' => '177', 'NazioneIt' => 'Qatar', 'NazioneEn' => 'Qatar'),
            array('NazioneID' => '178', 'NazioneIt' => 'Reunion', 'NazioneEn' => 'Reunion'),
            array('NazioneID' => '179', 'NazioneIt' => 'Romania', 'NazioneEn' => 'Romania'),
            array('NazioneID' => '180', 'NazioneIt' => 'Russia', 'NazioneEn' => 'Russian Federation'),
            array('NazioneID' => '181', 'NazioneIt' => 'Ruanda', 'NazioneEn' => 'Rwanda'),
            array('NazioneID' => '182', 'NazioneIt' => 'Saint Kitts e Nevis', 'NazioneEn' => 'Saint Kitts And Nevis'),
            array('NazioneID' => '183', 'NazioneIt' => 'Santa Lucia', 'NazioneEn' => 'Saint Lucia'),
            array('NazioneID' => '184', 'NazioneIt' => 'Saint Vincent e Grenadine', 'NazioneEn' => 'Saint Vincent And The Grenadines'),
            array('NazioneID' => '185', 'NazioneIt' => 'Samoa', 'NazioneEn' => 'Samoa'),
            array('NazioneID' => '186', 'NazioneIt' => 'San Marino', 'NazioneEn' => 'San Marino'),
            array('NazioneID' => '187', 'NazioneIt' => 'São Tomé e Príncipe', 'NazioneEn' => 'Sao Tome And Principe'),
            array('NazioneID' => '188', 'NazioneIt' => 'Arabia Saudita', 'NazioneEn' => 'Saudi Arabia'),
            array('NazioneID' => '189', 'NazioneIt' => 'Senegal', 'NazioneEn' => 'Senegal'),
            array('NazioneID' => '190', 'NazioneIt' => 'Seychelles', 'NazioneEn' => 'Seychelles'),
            array('NazioneID' => '191', 'NazioneIt' => 'Sierra Leone', 'NazioneEn' => 'Sierra Leone'),
            array('NazioneID' => '192', 'NazioneIt' => 'Singapore', 'NazioneEn' => 'Singapore'),
            array('NazioneID' => '193', 'NazioneIt' => 'Slovacchia', 'NazioneEn' => 'Slovakia'),
            array('NazioneID' => '194', 'NazioneIt' => 'Slovenia', 'NazioneEn' => 'Slovenia'),
            array('NazioneID' => '195', 'NazioneIt' => 'Isole Salomone', 'NazioneEn' => 'Solomon Islands'),
            array('NazioneID' => '196', 'NazioneIt' => 'Somalia', 'NazioneEn' => 'Somalia'),
            array('NazioneID' => '197', 'NazioneIt' => 'Sudafrica', 'NazioneEn' => 'South Africa'),
            array('NazioneID' => '198', 'NazioneIt' => 'Georgia del Sud e Isole Sandwich Meridionali', 'NazioneEn' => 'South Georgia And The South Sandwich Isl'),
            array('NazioneID' => '200', 'NazioneIt' => 'Spagna', 'NazioneEn' => 'Spain'),
            array('NazioneID' => '201', 'NazioneIt' => 'Sri Lanka', 'NazioneEn' => 'Sri Lanka'),
            array('NazioneID' => '202', 'NazioneIt' => 'St. Helena', 'NazioneEn' => 'St. Helena'),
            array('NazioneID' => '203', 'NazioneIt' => 'St. Pierre e Miquelon', 'NazioneEn' => 'St. Pierre And Miquelon'),
            array('NazioneID' => '204', 'NazioneIt' => 'Sudan', 'NazioneEn' => 'Sudan'),
            array('NazioneID' => '205', 'NazioneIt' => 'Suriname', 'NazioneEn' => 'Suriname'),
            array('NazioneID' => '206', 'NazioneIt' => 'Svalbard e Jan Mayen', 'NazioneEn' => 'Svalbard And Jan Mayen Islands'),
            array('NazioneID' => '207', 'NazioneIt' => 'Swaziland', 'NazioneEn' => 'Swaziland'),
            array('NazioneID' => '208', 'NazioneIt' => 'Svezia', 'NazioneEn' => 'Sweden'),
            array('NazioneID' => '209', 'NazioneIt' => 'Svizzera', 'NazioneEn' => 'Switzerland'),
            array('NazioneID' => '210', 'NazioneIt' => 'Siria', 'NazioneEn' => 'Syria'),
            array('NazioneID' => '212', 'NazioneIt' => 'Tahiti', 'NazioneEn' => 'Tahiti'),
            array('NazioneID' => '213', 'NazioneIt' => 'Taiwan', 'NazioneEn' => 'Taiwan, Province of China'),
            array('NazioneID' => '214', 'NazioneIt' => 'Tagikistan', 'NazioneEn' => 'Tajikistan'),
            array('NazioneID' => '215', 'NazioneIt' => 'Tanzania', 'NazioneEn' => 'Tanzania, United Republic Of'),
            array('NazioneID' => '216', 'NazioneIt' => 'Tailandia', 'NazioneEn' => 'Thailand'),
            array('NazioneID' => '217', 'NazioneIt' => 'Togo', 'NazioneEn' => 'Togo'),
            array('NazioneID' => '218', 'NazioneIt' => 'Tokelau', 'NazioneEn' => 'Tokelau'),
            array('NazioneID' => '219', 'NazioneIt' => 'Tonga', 'NazioneEn' => 'Tonga'),
            array('NazioneID' => '220', 'NazioneIt' => 'Trinidad e Tobago', 'NazioneEn' => 'Trinidad And Tobago'),
            array('NazioneID' => '221', 'NazioneIt' => 'Tunisia', 'NazioneEn' => 'Tunisia'),
            array('NazioneID' => '222', 'NazioneIt' => 'Turchia', 'NazioneEn' => 'Turkey'),
            array('NazioneID' => '223', 'NazioneIt' => 'Turkmenistan', 'NazioneEn' => 'Turkmenistan'),
            array('NazioneID' => '224', 'NazioneIt' => 'Isole Turks e Caicos', 'NazioneEn' => 'Turks And Caicos Islands'),
            array('NazioneID' => '225', 'NazioneIt' => 'Tuvalu', 'NazioneEn' => 'Tuvalu'),
            array('NazioneID' => '226', 'NazioneIt' => 'Uganda', 'NazioneEn' => 'Uganda'),
            array('NazioneID' => '227', 'NazioneIt' => 'Ucraina', 'NazioneEn' => 'Ukraine'),
            array('NazioneID' => '228', 'NazioneIt' => 'Emirati Arabi Uniti', 'NazioneEn' => 'United Arab Emirates'),
            array('NazioneID' => '229', 'NazioneIt' => 'Regno Unito', 'NazioneEn' => 'United Kingdom'),
            array('NazioneID' => '230', 'NazioneIt' => 'Isole minori esterne degli Stati Uniti d\'America', 'NazioneEn' => 'United States Minor Outlying Islands'),
            array('NazioneID' => '231', 'NazioneIt' => 'Stati Uniti', 'NazioneEn' => 'United States of America'),
            array('NazioneID' => '233', 'NazioneIt' => 'Uruguay', 'NazioneEn' => 'Uruguay'),
            array('NazioneID' => '234', 'NazioneIt' => 'Uzbekistan', 'NazioneEn' => 'Uzbekistan'),
            array('NazioneID' => '235', 'NazioneIt' => 'Vanuatu', 'NazioneEn' => 'Vanuatu'),
            array('NazioneID' => '236', 'NazioneIt' => 'Città del Vaticano', 'NazioneEn' => 'Vatican City State (Holy See)'),
            array('NazioneID' => '237', 'NazioneIt' => 'Venezuela', 'NazioneEn' => 'Venezuela'),
            array('NazioneID' => '238', 'NazioneIt' => 'Vietnam', 'NazioneEn' => 'Vietnam'),
            array('NazioneID' => '239', 'NazioneIt' => 'Isole Vergini Inglesi', 'NazioneEn' => 'Virgin Islands (British)'),
            array('NazioneID' => '240', 'NazioneIt' => 'Isole Vergini Americane', 'NazioneEn' => 'Virgin Islands (U.S)'),
            array('NazioneID' => '241', 'NazioneIt' => 'Isole Wallis e Futuna', 'NazioneEn' => 'Wallis And Futuna Islands'),
            array('NazioneID' => '242', 'NazioneIt' => 'Sahara Occidentale', 'NazioneEn' => 'Western Sahara'),
            array('NazioneID' => '243', 'NazioneIt' => 'Yemen', 'NazioneEn' => 'Yemen'),
            array('NazioneID' => '244', 'NazioneIt' => 'Yugoslavia', 'NazioneEn' => 'Yugoslavia'),
            array('NazioneID' => '245', 'NazioneIt' => 'Zaire', 'NazioneEn' => 'Zaire'),
            array('NazioneID' => '246', 'NazioneIt' => 'Zambia', 'NazioneEn' => 'Zambia'),
            array('NazioneID' => '247', 'NazioneIt' => 'Zimbabwe', 'NazioneEn' => 'Zimbabwe'),
        ));
    }

    public function safeDown() {
        $this->dropTable('nazioni');
        $this->dropTable('province');
        $this->dropTable('regioni');
        $this->dropTable('aree');
    }

}
